name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: copile
      run: make
    - name: run test read content
      run: make test-content
    - name: run test vangrid
      run: make test-vangrid
    - name: run test full
      run: make test-full
